#! /bin/sh

sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         0
bspc config window_gap          32

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Start polybar and picom
~/.config/polybar/launch.sh &
picom &

# Start Backgropund
~/.fehbg

# Change cursor
xsetroot -cursor_name left_ptr

xset dpms 0 0 0
xset dpms s off
